features = dict()

features["csp"] = [
"CSP-directive:script=src",
"CSP-directive:Default-src",
"CSP-directive:default-src",
"CSP-directive:script-src",
"CSP-directive:script-src-attr",
"CSP-directive:script-src-elem",
"CSP-value:nonascii",
"CSP-value:empty",
"CSP-value:capitalized-nonce",
"CSP-value:http://127.0.0.1:8080",
"CSP-value:http://127.0.0.1:8000",
"CSP-value:*",
"CSP-value:schemes",
"CSP-value:self",
"CSP-value:unsafe-inline",
"CSP-value:unsafe-eval",
"CSP-value:none",
"CSP-value:nonce",
"CSP-value:strict-dynamic",
"CSP-value:hash",
"CSP-value:unsafe-hashes"
]


features["page"] = [
"url-self",
"url-allowed",
"url-blocked",
"inline-script",
"location='[SCHEME]'",
"window.open('[SCHEME]')",
"location.replace('[SCHEME]')",
"eval('[JS]')",
"var o=document.createElement('script');o.src='[JS_RESOURCE]';document.body.appendChild(o);void(0);",
"var o=document.createElement('script');o.src='[JS_RESOURCE]';o.nonce=123;document.body.appendChild(o);void(0);",
"var o=document.createElement('iframe');o.src='[SCHEME]';document.body.appendChild(o);void(0);",
"var o=document.createElement('object');o.data='[SCHEME]';document.body.appendChild(o);void(0);",
"var o=document.createElement('iframe');o.src=[BLOB_HTML];document.body.appendChild(o);void(0);",
"var o=document.createElement('object');o.data=[BLOB_HTML];document.body.appendChild(o);void(0);",
"var o=document.createElement('script');o.src=[BLOB_JS];o.nonce=123;document.body.appendChild(o);void(0);",
"document.write('[HTML]')",
"location=[BLOB_HTML]",
"location.replace([BLOB_HTML])",
"window.open=[BLOB_HTML]",
"w=window.open('self.js'); w.document.write('[HTML]');",
"w=window.open('about:blank'); w.document.write('[HTML]');",
"javascript:'[HTML]'",
"javascript:[JS]",
"data:text/html,[HTML]",
"URL.createObjectURL(new Blob(['[HTML]'],{type:'text/html'}))",
"URL.createObjectURL(new Blob(['[JS]'],{type:'application/js'}))",
"<script>[JS]</script>",
"<script nonce=123>[JS]</script>",
"<script src=[JS_RESOURCE]></script>",
"<script src=[JS_RESOURCE] nonce=123></script>",
"<iframe src='[SCHEME]'></iframe>",
"<a id=ID_VAR href='[SCHEME]'></a><script>ID_VAR.click();</script>",
"<a id=ID_VAR href='[SCHEME]'></a><script nonce=123>ID_VAR.click();</script>",
"<object data='[SCHEME]'></object>",
"<li id=ID_VAR></li><script>ID_VAR.innerHTML+='[HTML]'</script>",
"<li id=ID_VAR></li><script nonce=123>ID_VAR.innerHTML+='[HTML]'</script>",
"<iframe srcdoc='[HTML]'></iframe>",
"<style>@keyframes ID_VAR{}</style><xss style=animation-name:ID_VAR onanimationstart='[JS]'></xss>",
"<audio oncanplay='[JS]'><source src=self.mp3 type=audio/mpeg></audio>",
"<audio controls ondurationchange='[JS]'><source src=self.mp3 type=audio/mpeg></audio>",
"<audio src/onerror='[JS]'></audio>",
"<audio autoplay onloadedmetadata='[JS]'><source src=self.mp3 type=audio/mpeg></audio>",
"<iframe onload='[JS]'></iframe>",
"<iframe id=ID_VAR src=about:blank></iframe><script>ID_VAR.onload=_=>ID_VAR.contentDocument.body.innerHTML+='[HTML]';ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script nonce=123>ID_VAR.onload=_=>ID_VAR.contentDocument.body.innerHTML+='[HTML]';ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script>ID_VAR.onload=_=>ID_VAR.contentDocument.write('[HTML]');ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script nonce=123>ID_VAR.onload=_=>ID_VAR.contentDocument.write('[HTML]');ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script>ID_VAR.addEventListener('load',()=>{ID_VAR.contentWindow.location.href='[SCHEME]';},{once:true});</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script nonce=123>ID_VAR.addEventListener('load',()=>{ID_VAR.contentWindow.location.href='[SCHEME]';},{once:true});</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script>ID_VAR.addEventListener('load',()=>{ID_VAR.src='[SCHEME]';},{once:true});</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script nonce=123>ID_VAR.addEventListener('load',()=>{ID_VAR.src='[SCHEME]';},{once:true});</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script>ID_VAR.addEventListener('load',()=>{ID_VAR.srcdoc='[HTML]';},{once:true});</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script nonce=123>ID_VAR.addEventListener('load',()=>{ID_VAR.srcdoc='[HTML]';},{once:true});</script>",
"<iframe id=ID_VAR src=self.html></iframe><script>ID_VAR.onload=_=>ID_VAR.contentDocument.body.innerHTML+='[HTML]';ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=self.html></iframe><script nonce=123>ID_VAR.onload=_=>ID_VAR.contentDocument.body.innerHTML+='[HTML]';ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=self.html></iframe><script>ID_VAR.onload=_=>ID_VAR.contentDocument.write('[HTML]');ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=self.html></iframe><script nonce=123>ID_VAR.onload=_=>ID_VAR.contentDocument.write('[HTML]');ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=self.html></iframe><script>ID_VAR.addEventListener('load',()=>{ID_VAR.contentWindow.location.href='[SCHEME]';},{once:true});</script>",
"<iframe id=ID_VAR src=self.html></iframe><script nonce=123>ID_VAR.addEventListener('load',()=>{ID_VAR.contentWindow.location.href='[SCHEME]';},{once:true});</script>",
"<iframe id=ID_VAR src=self.html></iframe><script>ID_VAR.addEventListener('load',()=>{ID_VAR.src='[SCHEME]';},{once:true});</script>",
"<iframe id=ID_VAR src=self.html></iframe><script nonce=123>ID_VAR.addEventListener('load',()=>{ID_VAR.src='[SCHEME]';},{once:true});</script>",
"<iframe id=ID_VAR src=self.html></iframe><script>ID_VAR.addEventListener('load',()=>{ID_VAR.srcdoc='[HTML]';},{once:true});</script>",
"<iframe id=ID_VAR src=self.html></iframe><script nonce=123>ID_VAR.addEventListener('load',()=>{ID_VAR.srcdoc='[HTML]';},{once:true});</script>",
"<form action='[SCHEME]' name=ID_VAR method=post></form><script>document.ID_VAR.submit();</script>",
"<form action='[SCHEME]' name=ID_VAR method=post></form><script nonce=123>document.ID_VAR.submit();</script>",
"<svg xmlns:svg=http://www.w3.org/2000/svg xmlns=http://www.w3.org/2000/svg xmlns:xlink=http://www.w3.org/1999/xlink>[HTML]</svg>",
"<iframe id=ID_VAR src=self.html></iframe><script>ID_VAR.onload=_=>ID_VAR.contentWindow.eval('[JS]');ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=self.html></iframe><script nonce=123>ID_VAR.onload=_=>ID_VAR.contentWindow.eval('[JS]');ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script>ID_VAR.onload=_=>ID_VAR.contentWindow.eval('[JS]');ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script nonce=123>ID_VAR.onload=_=>ID_VAR.contentWindow.eval('[JS]');ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script>ID_VAR.onload=_=>ID_VAR.contentWindow.eval('[JS]');ID_VAR.src='self.html';ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script nonce=123>ID_VAR.onload=_=>ID_VAR.contentWindow.eval('[JS]');ID_VAR.src='self.html';ID_VAR.contentWindow.location.reload();</script>",
"<template id=ID_VAR>[HTML]</template><script>document.body.appendChild(ID_VAR.content.cloneNode(true));</script>",
"<template id=ID_VAR>[HTML]</template><script nonce=123>document.body.appendChild(ID_VAR.content.cloneNode(true));</script>",
"<details ontoggle='[JS]' open>test</details>",
"<input id=ID_VAR onchange='[JS]' value=xss></input><script>var event = new Event('change');ID_VAR.dispatchEvent(event);</script>",
"<input id=ID_VAR onchange='[JS]' value=xss></input><script nonce=123>var event = new Event('change');ID_VAR.dispatchEvent(event);</script>",
"<xss id=ID_VAR onclick='[JS]' style=display:block>test</xss><script>var event = new Event('click');ID_VAR.dispatchEvent(event);</script>",
"<xss id=ID_VAR onclick='[JS]' style=display:block>test</xss><script nonce=123>var event = new Event('click');ID_VAR.dispatchEvent(event);</script>",
"<xss id=ID_VAR oncopy='[JS]' value=test autofocus tabindex=1 style=display:block>test</xss><script>var event = new Event('copy');ID_VAR.dispatchEvent(event);</script>",
"<xss id=ID_VAR oncopy='[JS]' value=test autofocus tabindex=1 style=display:block>test</xss><script nonce=123>var event = new Event('copy');ID_VAR.dispatchEvent(event);</script>",
"<input id=ID_VAR oninput='[JS]' value=test></input><script>var event = new Event('input');ID_VAR.dispatchEvent(event);</script>",
"<input id=ID_VAR oninput='[JS]' value=test></input><script nonce=123>var event = new Event('input');ID_VAR.dispatchEvent(event);</script>"
]

features["browser"] = [
  "Chrome",
  "Firefox",
  "Safari"
]

features["status"] = 200


col_names = [
"CSP-directive:script=src",
"CSP-directive:Default-src",
"CSP-directive:default-src",
"CSP-directive:script-src",
"CSP-directive:script-src-attr",
"CSP-directive:script-src-elem",
"CSP-value:nonascii",
"CSP-value:empty",
"CSP-value:capitalized-nonce",
"CSP-value:http://127.0.0.1:8080",
"CSP-value:http://127.0.0.1:8000",
"CSP-value:*",
"CSP-value:schemes",
"CSP-value:self",
"CSP-value:unsafe-inline",
"CSP-value:unsafe-eval",
"CSP-value:none",
"CSP-value:nonce",
"CSP-value:strict-dynamic",
"CSP-value:hash",
"CSP-value:unsafe-hashes",
"url-self",
"url-allowed",
"url-blocked",
"inline-script",
"location='[SCHEME]'",
"window.open('[SCHEME]')",
"location.replace('[SCHEME]')",
"eval('[JS]')",
"var o=document.createElement('script');o.src='[JS_RESOURCE]';document.body.appendChild(o);void(0);",
"var o=document.createElement('script');o.src='[JS_RESOURCE]';o.nonce=123;document.body.appendChild(o);void(0);",
"var o=document.createElement('iframe');o.src='[SCHEME]';document.body.appendChild(o);void(0);",
"var o=document.createElement('object');o.data='[SCHEME]';document.body.appendChild(o);void(0);",
"var o=document.createElement('iframe');o.src=[BLOB_HTML];document.body.appendChild(o);void(0);",
"var o=document.createElement('object');o.data=[BLOB_HTML];document.body.appendChild(o);void(0);",
"var o=document.createElement('script');o.src=[BLOB_JS];o.nonce=123;document.body.appendChild(o);void(0);",
"document.write('[HTML]')",
"location=[BLOB_HTML]",
"location.replace([BLOB_HTML])",
"window.open=[BLOB_HTML]",
"w=window.open('self.js'); w.document.write('[HTML]');",
"w=window.open('about:blank'); w.document.write('[HTML]');",
"javascript:'[HTML]'",
"javascript:[JS]",
"data:text/html,[HTML]",
"URL.createObjectURL(new Blob(['[HTML]'],{type:'text/html'}))",
"URL.createObjectURL(new Blob(['[JS]'],{type:'application/js'}))",
"<script>[JS]</script>",
"<script nonce=123>[JS]</script>",
"<script src=[JS_RESOURCE]></script>",
"<script src=[JS_RESOURCE] nonce=123></script>",
"<iframe src='[SCHEME]'></iframe>",
"<a id=ID_VAR href='[SCHEME]'></a><script>ID_VAR.click();</script>",
"<a id=ID_VAR href='[SCHEME]'></a><script nonce=123>ID_VAR.click();</script>",
"<object data='[SCHEME]'></object>",
"<li id=ID_VAR></li><script>ID_VAR.innerHTML+='[HTML]'</script>",
"<li id=ID_VAR></li><script nonce=123>ID_VAR.innerHTML+='[HTML]'</script>",
"<iframe srcdoc='[HTML]'></iframe>",
"<style>@keyframes ID_VAR{}</style><xss style=animation-name:ID_VAR onanimationstart='[JS]'></xss>",
"<audio oncanplay='[JS]'><source src=self.mp3 type=audio/mpeg></audio>",
"<audio controls ondurationchange='[JS]'><source src=self.mp3 type=audio/mpeg></audio>",
"<audio src/onerror='[JS]'></audio>",
"<audio autoplay onloadedmetadata='[JS]'><source src=self.mp3 type=audio/mpeg></audio>",
"<iframe onload='[JS]'></iframe>",
"<iframe id=ID_VAR src=about:blank></iframe><script>ID_VAR.onload=_=>ID_VAR.contentDocument.body.innerHTML+='[HTML]';ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script nonce=123>ID_VAR.onload=_=>ID_VAR.contentDocument.body.innerHTML+='[HTML]';ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script>ID_VAR.onload=_=>ID_VAR.contentDocument.write('[HTML]');ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script nonce=123>ID_VAR.onload=_=>ID_VAR.contentDocument.write('[HTML]');ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script>ID_VAR.addEventListener('load',()=>{ID_VAR.contentWindow.location.href='[SCHEME]';},{once:true});</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script nonce=123>ID_VAR.addEventListener('load',()=>{ID_VAR.contentWindow.location.href='[SCHEME]';},{once:true});</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script>ID_VAR.addEventListener('load',()=>{ID_VAR.src='[SCHEME]';},{once:true});</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script nonce=123>ID_VAR.addEventListener('load',()=>{ID_VAR.src='[SCHEME]';},{once:true});</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script>ID_VAR.addEventListener('load',()=>{ID_VAR.srcdoc='[HTML]';},{once:true});</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script nonce=123>ID_VAR.addEventListener('load',()=>{ID_VAR.srcdoc='[HTML]';},{once:true});</script>",
"<iframe id=ID_VAR src=self.html></iframe><script>ID_VAR.onload=_=>ID_VAR.contentDocument.body.innerHTML+='[HTML]';ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=self.html></iframe><script nonce=123>ID_VAR.onload=_=>ID_VAR.contentDocument.body.innerHTML+='[HTML]';ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=self.html></iframe><script>ID_VAR.onload=_=>ID_VAR.contentDocument.write('[HTML]');ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=self.html></iframe><script nonce=123>ID_VAR.onload=_=>ID_VAR.contentDocument.write('[HTML]');ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=self.html></iframe><script>ID_VAR.addEventListener('load',()=>{ID_VAR.contentWindow.location.href='[SCHEME]';},{once:true});</script>",
"<iframe id=ID_VAR src=self.html></iframe><script nonce=123>ID_VAR.addEventListener('load',()=>{ID_VAR.contentWindow.location.href='[SCHEME]';},{once:true});</script>",
"<iframe id=ID_VAR src=self.html></iframe><script>ID_VAR.addEventListener('load',()=>{ID_VAR.src='[SCHEME]';},{once:true});</script>",
"<iframe id=ID_VAR src=self.html></iframe><script nonce=123>ID_VAR.addEventListener('load',()=>{ID_VAR.src='[SCHEME]';},{once:true});</script>",
"<iframe id=ID_VAR src=self.html></iframe><script>ID_VAR.addEventListener('load',()=>{ID_VAR.srcdoc='[HTML]';},{once:true});</script>",
"<iframe id=ID_VAR src=self.html></iframe><script nonce=123>ID_VAR.addEventListener('load',()=>{ID_VAR.srcdoc='[HTML]';},{once:true});</script>",
"<form action='[SCHEME]' name=ID_VAR method=post></form><script>document.ID_VAR.submit();</script>",
"<form action='[SCHEME]' name=ID_VAR method=post></form><script nonce=123>document.ID_VAR.submit();</script>",
"<svg xmlns:svg=http://www.w3.org/2000/svg xmlns=http://www.w3.org/2000/svg xmlns:xlink=http://www.w3.org/1999/xlink>[HTML]</svg>",
"<iframe id=ID_VAR src=self.html></iframe><script>ID_VAR.onload=_=>ID_VAR.contentWindow.eval('[JS]');ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=self.html></iframe><script nonce=123>ID_VAR.onload=_=>ID_VAR.contentWindow.eval('[JS]');ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script>ID_VAR.onload=_=>ID_VAR.contentWindow.eval('[JS]');ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script nonce=123>ID_VAR.onload=_=>ID_VAR.contentWindow.eval('[JS]');ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script>ID_VAR.onload=_=>ID_VAR.contentWindow.eval('[JS]');ID_VAR.src='self.html';ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script nonce=123>ID_VAR.onload=_=>ID_VAR.contentWindow.eval('[JS]');ID_VAR.src='self.html';ID_VAR.contentWindow.location.reload();</script>",
"<template id=ID_VAR>[HTML]</template><script>document.body.appendChild(ID_VAR.content.cloneNode(true));</script>",
"<template id=ID_VAR>[HTML]</template><script nonce=123>document.body.appendChild(ID_VAR.content.cloneNode(true));</script>",
"<details ontoggle='[JS]' open>test</details>",
"<input id=ID_VAR onchange='[JS]' value=xss></input><script>var event = new Event('change');ID_VAR.dispatchEvent(event);</script>",
"<input id=ID_VAR onchange='[JS]' value=xss></input><script nonce=123>var event = new Event('change');ID_VAR.dispatchEvent(event);</script>",
"<xss id=ID_VAR onclick='[JS]' style=display:block>test</xss><script>var event = new Event('click');ID_VAR.dispatchEvent(event);</script>",
"<xss id=ID_VAR onclick='[JS]' style=display:block>test</xss><script nonce=123>var event = new Event('click');ID_VAR.dispatchEvent(event);</script>",
"<xss id=ID_VAR oncopy='[JS]' value=test autofocus tabindex=1 style=display:block>test</xss><script>var event = new Event('copy');ID_VAR.dispatchEvent(event);</script>",
"<xss id=ID_VAR oncopy='[JS]' value=test autofocus tabindex=1 style=display:block>test</xss><script nonce=123>var event = new Event('copy');ID_VAR.dispatchEvent(event);</script>",
"<input id=ID_VAR oninput='[JS]' value=test></input><script>var event = new Event('input');ID_VAR.dispatchEvent(event);</script>",
"<input id=ID_VAR oninput='[JS]' value=test></input><script nonce=123>var event = new Event('input');ID_VAR.dispatchEvent(event);</script>",
"Chrome",
"Firefox",
"Safari",
"status",
"label"
]

reduced_col_names = [
"CSP-directive:script=src",
"CSP-directive:Default-src",
"CSP-directive:default-src",
"CSP-directive:script-src",
"CSP-directive:script-src-attr",
"CSP-directive:script-src-elem",
"CSP-value:nonascii",
"CSP-value:empty",
"CSP-value:capitalized-nonce",
"CSP-value:http://127.0.0.1:8080",
"CSP-value:http://127.0.0.1:8000",
"CSP-value:*",
"CSP-value:schemes",
"CSP-value:self",
"CSP-value:unsafe-inline",
"CSP-value:unsafe-eval",
"CSP-value:none",
"CSP-value:nonce",
"CSP-value:strict-dynamic",
"CSP-value:hash",
"CSP-value:unsafe-hashes",
"JS_EXECUTION_METHOD",
"eval('[JS]')",
"[Tagged inline JS]",
"[Expending current HTML]",
"[JS fetching in HTML]",
"[JS fetching in JS]",
"[Redirect to scheme]",
"[Event Handler]",
"[Write to about:blank]",
"[Change location of about:blank]",
"[Write to static file]",
"[Change location of static file]",
"[Srcdoc write]",
"[Eval of child frame]",
"Chrome",
"Firefox",
"Safari",
"status",
]

merged_content = {
        "[Tagged inline JS]": [
           "<script>[JS]</script>",
           "<script nonce=123>[JS]</script>"
        ],
        "[Expending current HTML]": [
            "<li id=ID_VAR></li><script>ID_VAR.innerHTML+='[HTML]'</script>",
            "<li id=ID_VAR></li><script nonce=123>ID_VAR.innerHTML+='[HTML]'</script>",
            "<template id=ID_VAR>[HTML]</template><script>document.body.appendChild(ID_VAR.content.cloneNode(true));</script>",
            "<template id=ID_VAR>[HTML]</template><script nonce=123>document.body.appendChild(ID_VAR.content.cloneNode(true));</script>",
            "<svg xmlns:svg=http://www.w3.org/2000/svg xmlns=http://www.w3.org/2000/svg xmlns:xlink=http://www.w3.org/1999/xlink>[HTML]</svg>",
            "document.write('[HTML]')"
        ],
        "[JS fetching in HTML]": [
           "<script>[JS]</script>",
           "<script nonce=123>[JS]</script>"
        ],
        "[JS fetching in JS]": [
            "var o=document.createElement('script');o.src='[JS_RESOURCE]';document.body.appendChild(o);void(0);",
            "var o=document.createElement('script');o.src='[JS_RESOURCE]';o.nonce=123;document.body.appendChild(o);void(0);"

        ],
        "[Redirect to scheme]": [
            "<a id=ID_VAR href='[SCHEME]'></a><script>ID_VAR.click();</script>",
            "<a id=ID_VAR href='[SCHEME]'></a><script nonce=123>ID_VAR.click();</script>",
            "<object data='[SCHEME]'></object>",
            "<iframe src='[SCHEME]'></iframe>",
            "<form action='[SCHEME]' name=ID_VAR method=post></form><script>document.ID_VAR.submit();</script>",
            "<form action='[SCHEME]' name=ID_VAR method=post></form><script nonce=123>document.ID_VAR.submit();</script>",
            "location='[SCHEME]'",
            "window.open('[SCHEME]')",
            "location.replace('[SCHEME]')",
            "location=[BLOB_HTML]",
            "location.replace([BLOB_HTML])",
            "window.open=[BLOB_HTML]",
            "javascript:[JS]",
            "javascript:'[HTML]'",
            "data:text/html,[HTML]",
            "URL.createObjectURL(new Blob(['[HTML]'],{type:'text/html'}))",
            "URL.createObjectURL(new Blob(['[JS]'],{type:'application/js'}))",
            "var o=document.createElement('iframe');o.src='[SCHEME]';document.body.appendChild(o);void(0);",
            "var o=document.createElement('object');o.data='[SCHEME]';document.body.appendChild(o);void(0);",
            "var o=document.createElement('iframe');o.src=[BLOB_HTML];document.body.appendChild(o);void(0);",
            "var o=document.createElement('object');o.data=[BLOB_HTML];document.body.appendChild(o);void(0);",
            "var o=document.createElement('script');o.src=[BLOB_JS];o.nonce=123;document.body.appendChild(o);void(0);"
        ],
        "[Event Handler]": [
            "<style>@keyframes ID_VAR{}</style><xss style=animation-name:ID_VAR onanimationstart='[JS]'></xss>",
            "<audio oncanplay='[JS]'><source src=self.mp3 type=audio/mpeg></audio>",
            "<audio controls ondurationchange='[JS]'><source src=self.mp3 type=audio/mpeg></audio>",
            "<audio src/onerror='[JS]'></audio>",
            "<audio autoplay onloadedmetadata='[JS]'><source src=self.mp3 type=audio/mpeg></audio>",
            "<iframe onload='[JS]'></iframe>",
            "<details ontoggle='[JS]' open>test</details>",
            "<input id=ID_VAR onchange='[JS]' value=xss></input><script>var event = new Event('change');ID_VAR.dispatchEvent(event);</script>",
            "<input id=ID_VAR onchange='[JS]' value=xss></input><script nonce=123>var event = new Event('change');ID_VAR.dispatchEvent(event);</script>",
            "<xss id=ID_VAR onclick='[JS]' style=display:block>test</xss><script>var event = new Event('click');ID_VAR.dispatchEvent(event);</script>",
            "<xss id=ID_VAR onclick='[JS]' style=display:block>test</xss><script nonce=123>var event = new Event('click');ID_VAR.dispatchEvent(event);</script>",
            "<xss id=ID_VAR oncopy='[JS]' value=test autofocus tabindex=1 style=display:block>test</xss><script>var event = new Event('copy');ID_VAR.dispatchEvent(event);</script>",
            "<xss id=ID_VAR oncopy='[JS]' value=test autofocus tabindex=1 style=display:block>test</xss><script nonce=123>var event = new Event('copy');ID_VAR.dispatchEvent(event);</script>",
            "<input id=ID_VAR oninput='[JS]' value=test></input><script>var event = new Event('input');ID_VAR.dispatchEvent(event);</script>",
            "<input id=ID_VAR oninput='[JS]' value=test></input><script nonce=123>var event = new Event('input');ID_VAR.dispatchEvent(event);</script>"
        ],
"[Write to about:blank]": [
"<iframe id=ID_VAR src=about:blank></iframe><script>ID_VAR.onload=_=>ID_VAR.contentDocument.body.innerHTML+='[HTML]';ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script nonce=123>ID_VAR.onload=_=>ID_VAR.contentDocument.body.innerHTML+='[HTML]';ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script>ID_VAR.onload=_=>ID_VAR.contentDocument.write('[HTML]');ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script nonce=123>ID_VAR.onload=_=>ID_VAR.contentDocument.write('[HTML]');ID_VAR.contentWindow.location.reload();</script>",
"w=window.open('about:blank'); w.document.write('[HTML]');"
        ],
"[Change location of about:blank]": [
"<iframe id=ID_VAR src=about:blank></iframe><script>ID_VAR.addEventListener('load',()=>{ID_VAR.contentWindow.location.href='[SCHEME]';},{once:true});</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script nonce=123>ID_VAR.addEventListener('load',()=>{ID_VAR.contentWindow.location.href='[SCHEME]';},{once:true});</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script>ID_VAR.addEventListener('load',()=>{ID_VAR.src='[SCHEME]';},{once:true});</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script nonce=123>ID_VAR.addEventListener('load',()=>{ID_VAR.src='[SCHEME]';},{once:true});</script>"
        ],
"[Write to static file]": [
"<iframe id=ID_VAR src=self.html></iframe><script>ID_VAR.onload=_=>ID_VAR.contentDocument.body.innerHTML+='[HTML]';ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=self.html></iframe><script nonce=123>ID_VAR.onload=_=>ID_VAR.contentDocument.body.innerHTML+='[HTML]';ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=self.html></iframe><script>ID_VAR.onload=_=>ID_VAR.contentDocument.write('[HTML]');ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=self.html></iframe><script nonce=123>ID_VAR.onload=_=>ID_VAR.contentDocument.write('[HTML]');ID_VAR.contentWindow.location.reload();</script>",
"w=window.open('self.js'); w.document.write('[HTML]');"
        ],
"[Change location of static file]": [
"<iframe id=ID_VAR src=self.html></iframe><script>ID_VAR.addEventListener('load',()=>{ID_VAR.contentWindow.location.href='[SCHEME]';},{once:true});</script>",
"<iframe id=ID_VAR src=self.html></iframe><script nonce=123>ID_VAR.addEventListener('load',()=>{ID_VAR.contentWindow.location.href='[SCHEME]';},{once:true});</script>",
"<iframe id=ID_VAR src=self.html></iframe><script>ID_VAR.addEventListener('load',()=>{ID_VAR.src='[SCHEME]';},{once:true});</script>",
"<iframe id=ID_VAR src=self.html></iframe><script nonce=123>ID_VAR.addEventListener('load',()=>{ID_VAR.src='[SCHEME]';},{once:true});</script>"
        ],
"[Srcdoc write]": [
"<iframe srcdoc='[HTML]'></iframe>",
"<iframe id=ID_VAR src=about:blank></iframe><script>ID_VAR.addEventListener('load',()=>{ID_VAR.srcdoc='[HTML]';},{once:true});</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script nonce=123>ID_VAR.addEventListener('load',()=>{ID_VAR.srcdoc='[HTML]';},{once:true});</script>",
"<iframe id=ID_VAR src=self.html></iframe><script>ID_VAR.addEventListener('load',()=>{ID_VAR.srcdoc='[HTML]';},{once:true});</script>",
"<iframe id=ID_VAR src=self.html></iframe><script nonce=123>ID_VAR.addEventListener('load',()=>{ID_VAR.srcdoc='[HTML]';},{once:true});</script>"
        ],
"[Eval of child frame]": [
"<iframe id=ID_VAR src=self.html></iframe><script>ID_VAR.onload=_=>ID_VAR.contentWindow.eval('[JS]');ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=self.html></iframe><script nonce=123>ID_VAR.onload=_=>ID_VAR.contentWindow.eval('[JS]');ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script>ID_VAR.onload=_=>ID_VAR.contentWindow.eval('[JS]');ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script nonce=123>ID_VAR.onload=_=>ID_VAR.contentWindow.eval('[JS]');ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script>ID_VAR.onload=_=>ID_VAR.contentWindow.eval('[JS]');ID_VAR.src='self.html';ID_VAR.contentWindow.location.reload();</script>",
"<iframe id=ID_VAR src=about:blank></iframe><script nonce=123>ID_VAR.onload=_=>ID_VAR.contentWindow.eval('[JS]');ID_VAR.src='self.html';ID_VAR.contentWindow.location.reload();</script>"
        ]

}
